[theme]
primaryColor = "#8B5C2A"              # Rich brown for highlights/buttons
backgroundColor = "#FDF6E3"           # Parchment/cream background
secondaryBackgroundColor = "#F5E6C8"  # Slightly darker cream for panels
textColor = "#3E2723"                 # Dark brown for text
font = "serif"
